### ISSUE TITLE
observability.InitTracerProvider breaks interface segregation principle

### ISSUE THREAD

**Issue by fedulovivan** [DoWithLogic/golang-clean-architecture#32]
It would be better to receive a part of whole app config related to the tracer initialization only, rather than using `config config.Config`.

**Comment by martinyonatann** [comment]
Thanks for the suggestion! I agree that passing the entire config.Config isn’t necessary when initializing the tracer. I’ll fix this by only passing the part of the config that’s related to tracer setup.

If possible, I’d prefer if you could make a PR for this. Thanks again for your input!
